### ISSUE TITLE
[QUESTION] "No matched Process", Is this only for PHP5 and apache2?

### ISSUE THREAD

**Issue by rocketinventor** [padosoft/kill-process#1]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [-] I have read and understood the [contributors guide]().
- [-] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [-] I have checked that the bug-fix I am reporting can be replicated.

---

### Description of the problem
Whenever I run the script (in usage screenshots, too), I see:
```Check /usr/sbin/apache2 process...
There isn't any matched process for /usr/sbin/apache2
Check /usr/bin/php5-cgi process...
There isn't any matched process for /usr/bin/php5-cgi
```
I was expecting it to either:
- automatically kill high cpu processes
or
- kill high cpu processes on demand. 
It doesn't seem to do either and I'm not sure why it is specifically checking those two locations. Perhaps some documentation would be useful?
### Steps to reproduce
run ` bash killprocess.sh kill top cpu

Thanks!

**Comment by lopadova** [comment]
Hi @rocketinventor ,
the script is not just for php, it can be used to intercept any process.

The operation of the script, however, expected to detect only the processes listed in **KILLLIST** variable.
By default this variable is set to detect or processes "/ usr / sbin / apache2" and "/ usr / bin / php5-cgi"
but you feel free to detect any process and add it to the list.

If you want to control any type of process, then you can do this fast and dirty tricks without changing the script:
- 1) placing empty process '' (two quote char) in the list: 
`KILLLIST = ("''")`

- 2) use the ps command with time sort
Here is the command:
`bash killprocess.sh kill ps time`

I hope this trick solves your problem.
