### ISSUE TITLE
[Question] tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by Betaman2k** [padosoft/kill-process#2]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ yes] I have read and understood the [contributors guide]().
- [ yes] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ yes] I have checked that the bug-fix I am reporting can be replicated.

---

### Description of the problem
I check my killprocess.log, i get this info

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Process execute in 'kill' mode.
Process fetched by 'top' command
Process sort by %CPU ( 9 )
Check /usr/bin/xxx process...
There isn't any matched process for /usr/bin/xxx

### Steps to reproduce

Modify only this

#max cpu % load
MAX_CPU=95
#max execution time for CPU percentage > MAX_CPU (in seconds 7200s=2h)
MAX_SEC=180
#max execution time for any %CPU (in seconds 2700s=45min)
MAX_SEC2=270

my crontab

0       *       *       *       *       bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1
5       *       *       *       *       bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1
10      *       *       *       *       bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1

is my logfiles OK, or is wrong ?
cya
Betaman

**Comment by lopadova** [comment]
Hi,
the problem probabily is that the script use color syntax and when you run it by cron the enviroment variable $TERM is not set.
If no $TERM variable is set, cron will emit a "tput: No value for $TERM and no -T" specified error.
If you run the killprocess.sh by manual shell, you obtain the same result or you notice the warning only via CRON?
Try to set $TERM in your cron (TERM=xterm) or remove every color syntex in the script.

To set $TERM in your cron try this:

```

TERM=xterm

0 * * * * bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1
5 * * * * bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1
10 * * * * bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1

```

You can change xterm with another available terminal in your system like dumb.

Give me the feedback.

Thanks,
Lorenzo.

**Comment by Betaman2k** [comment]
Hi

now i used only this on my crontab

`TERM=xterm
* * * * *       bash /root/myscript/kill-process/killprocess.sh kill top cpu > /var/log/killprocess.log 2>&1
`

git  killed my stars hehe ( * * * * * )

log file now:

[31mProcess execute in 'kill' mode.(B[m
Process fetched by '[33mtop(B[m' command
Process sort by [33m%CPU(B[m ( 9 )
Check [33m/usr/bin/xxx(B[m process...
[32mThere isn't any matched process for /usr/bin/xxx(B[m

**Comment by lopadova** [comment]
Ok.
The warinng is not present.
Symbols are colors chars. 
In shell you will see the color in output.
You can try to change TERM var in cron or remove the colors chars.

The script however works correct.

Thanks.

**Comment by Betaman2k** [comment]
Hi

yeah
i change this:

#RED=`tput setaf 1`
#GREEN=`tput setaf 2`
#YELLOW=`tput setaf 3`
#NC=`tput sgr0` # No Color

my log is now fine

Process execute in 'kill' mode.
Process fetched by 'top' command
Process sort by %CPU ( 9 )
Check /usr/bin/xxx process...
There isn't any matched process for /usr/bin/xxx

crontab check now every minute with one thread ( i hope is correct )

is the time correct on the script

#max execution time for CPU percentage > MAX_CPU (in seconds 7200s=2h)
MAX_SEC=180
#max execution time for any %CPU (in seconds 2700s=45min)
MAX_SEC2=270

or to fast ?
cya
Betaman

**Comment by lopadova** [comment]
great!

As for these settings depend on the server you have, the routine running and finally how you want to be tolerant. 
For my server in production values ​​seems a little too low in my opinion.

Lorenzo.
